//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikMak2016.App_Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ProductArticle = new HashSet<ProductArticle>();
        }
    
        public string Number { get; set; }
        public string StandardCost { get; set; }
        public string Name { get; set; }
        public string Breadth { get; set; }
        public string GrossWeight { get; set; }
        public int IdArticleType { get; set; }
        public string RestockingTerm { get; set; }
        public int IdUnitBase { get; set; }
        public string UnitPrice { get; set; }
        public int IdSupplier { get; set; }
        public string Image { get; set; }
        public int Id { get; set; }
        public string InsertedBy { get; set; }
        public string InsertedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedOn { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual UnitBase UnitBase { get; set; }
        public virtual ICollection<ProductArticle> ProductArticle { get; set; }
    }
}
