//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikMak2016.App_Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductArticle
    {
        public int IdProduct { get; set; }
        public int IdArticle { get; set; }
        public int Id { get; set; }
        public string Quantity { get; set; }
        public string InsertedBy { get; set; }
        public string InsertedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedOn { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
